# Generated by Django 3.0.4 on 2020-05-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('state', models.SmallIntegerField()),
                ('timer', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.SmallIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('grades', models.SmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='cur_player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_turn', to='hat.Player'),
        ),
    ]
