# Generated by Django 3.0.4 on 2020-05-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cur_player',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_turng1', to='hat.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='timer',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='grades',
            field=models.SmallIntegerField(default=0),
        ),
    ]
