# Generated by Django 3.0.4 on 2020-05-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0004_auto_20200507_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='wordsnum',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='cur_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_turn', to='hat.Player'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('checked', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.Player')),
            ],
        ),
    ]
