# Generated by Django 3.0.4 on 2020-05-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0006_player_cur_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cur_player',
        ),
        migrations.AddField(
            model_name='game',
            name='begin_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
