# Generated by Django 3.0.4 on 2020-05-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0007_auto_20200508_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='seconds',
            field=models.SmallIntegerField(default=60),
        ),
    ]
