# Generated by Django 3.0.4 on 2020-05-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0008_game_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='roundsnum',
            field=models.SmallIntegerField(default=3),
        ),
    ]
