# Generated by Django 3.0.4 on 2020-05-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0009_game_roundsnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.Player')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.Word')),
            ],
        ),
    ]
