# Generated by Django 3.0.4 on 2020-05-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0011_game_elapsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='begin_number',
        ),
    ]
